#!/usr/bin/env sh

echo 'Installing lints through brew'
# cppcheck -> C/C++
# golangci/tap/golangci-lint -> Go
# hadolint -> Dockerfile
# icarus-verilog -> Verilog
# llvm -> C/C++
# shellcheck -> sh
# shfmt -> sh
brew install \
    cppcheck \
    golangci/tap/golangci-lint \
    hadolint \
    icarus-verilog \
    llvm \
    shellcheck \
    shfmt

echo 'Linking LLVM Lints'
ln -s "$(brew --prefix llvm)/bin/clang-format" "/usr/local/bin/clang-format"
ln -s "$(brew --prefix llvm)/bin/clang-tidy" "/usr/local/bin/clang-tidy"

echo 'Installing lints through pip'
# cmakelint -> Cmake
# proselint -> Tex/Latex/Markdown/Text
# pylint -> Python
# vim-vint -> Vim
# yamllint -> YAML
pip install \
    cmakelint \
    proselint \
    pylint \
    vim-vint \
    yamllint

echo 'JavaScript Lint'
sudo npm install standard --global
